FROM golang:1.19-alpine

RUN apk add --no-cache --update git

RUN go env -w GO111MODULE=off
WORKDIR /go/src/api
COPY . .

RUN go get -d -v \
  && go install -v \
  && go build

EXPOSE 3000
CMD ["./api"]
